.PHONY: clean All

All:
	@echo "----------Building project:[ EjemploPasoReferencia - Debug ]----------"
	@cd "EjemploPasoReferencia" && "$(MAKE)" -f  "EjemploPasoReferencia.mk"
clean:
	@echo "----------Cleaning project:[ EjemploPasoReferencia - Debug ]----------"
	@cd "EjemploPasoReferencia" && "$(MAKE)" -f  "EjemploPasoReferencia.mk" clean
