.PHONY: clean All

All:
	@echo "----------Building project:[ EjemploPasoReferencia2 - Debug ]----------"
	@cd "EjemploPasoReferencia2" && "$(MAKE)" -f  "EjemploPasoReferencia2.mk"
clean:
	@echo "----------Cleaning project:[ EjemploPasoReferencia2 - Debug ]----------"
	@cd "EjemploPasoReferencia2" && "$(MAKE)" -f  "EjemploPasoReferencia2.mk" clean
